### ISSUE TITLE
Contrast between selected and highlighted line too low

### ISSUE THREAD

**Issue by Jiehong** [subtheme-dev/monokai-pro#24]
**Describe the bug**
The contrast / colour difference between the selection and the current line is too low, leading to being unsure was is exactly selected.

**To Reproduce**
1. Install monokai-pro in intellij ultimate edition (having tried in other editions)
2. Select the Filter Spectrum variant
3. Open a java file (or any other file)
4. select some text in the current line (see screenshot: it's a Jenkinsfile, aka a Groovy file, but it's the same for other types)

**Screenshots**
![image](https://user-images.githubusercontent.com/1061229/131499030-fe12494e-6a3b-4a94-8ec3-e450a8a717bc.png)

**Application:**
Intellij IDEA ultimate (not tried in others)

**Comment by espositocode** [comment]
Thanks for pointing this out. Updated in 1.5: https://plugins.jetbrains.com/plugin/13643-monokai-pro-theme/versions/stable/137420
