### ISSUE TITLE
TODO Statments are not highlighted in the scroolbar

### ISSUE THREAD

**Issue by HentaiOusama** [subtheme-dev/monokai-pro#26]
**Describe the bug**
Just like we see small and thin horizontal lines in the scrollbar of the editor for errors (red) and warnings (yellow), we should be able to see a similar line (probably of blue color) for TODO comments which we can see in IntelliJ Light Theme but not in Monokai Pro.

**To Reproduce**
1. Write a Todo comment anywhere in the editor (E.g.  // TODO: This is a comment)
2. In IntelliJ Light Theme, we will see a thin blue horizontal line on the scrollbar.
3. If we switch to Monokai Pro, no such corresponding line will be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/56789471/135733378-a9d3c2d9-df41-46dc-8435-59926429ffcc.png)
![image](https://user-images.githubusercontent.com/56789471/135733385-21eb6a4c-b69a-4faf-8a16-f63ca3d52e2c.png)

**Application:**
All JetBrain IDEs

**Comment by HentaiOusama** [comment]
I have created a pull request to fix this issue. Please merge that request and close this issue.

**Comment by espositocode** [comment]
Thanks, and sorry for the delay. The changes look good.
