### ISSUE TITLE
Tool window bars are black and impossible to read

### ISSUE THREAD

**Issue by domnministru** [subtheme-dev/monokai-pro#35]
All toolbars are becoming black, right after theme installing and are not being changed until you reset IDE
I've searched for settings to change their colors but it seems there is nothing to fix it

![image](https://user-images.githubusercontent.com/36744282/162942582-fc2b6758-7460-466c-b6f5-2a3adfb13491.png)
![image](https://user-images.githubusercontent.com/36744282/162942600-819644da-6a8b-4184-abe3-bfc5abe32ae4.png)
![image](https://user-images.githubusercontent.com/36744282/162942625-90370bfe-729e-4f27-bba5-f15e3a724592.png)

**Comment by amm834** [comment]
Me too. I'm facing this issue in my webstorm 2022.* version.

**Comment by espositocode** [comment]
Dupe: https://github.com/subtheme-dev/monokai-pro/issues/31
