### ISSUE TITLE
Title of TitledBorder is unreadable

### ISSUE THREAD

**Issue by DevCharly** [subtheme-dev/monokai-pro#37]
**Describe the bug**
When using a `javax.swing.border.TitledBorder`, the title is unreadable because the color `TitledBorder.titleColor` is set to a background color. But this is the color of the text and should be set to a foreground color.

**Screenshots**

![image](https://user-images.githubusercontent.com/5604048/165759231-232d61e6-5c92-4671-aaf7-8a75d7a8eeb5.png)

Expected:

![image](https://user-images.githubusercontent.com/5604048/165759077-2ea7d7f7-8049-4aad-9185-0a6a4181016e.png)

**Comment by espositocode** [comment]
Is there a particular place in the UI, like somewhere in the Preferences page, where I can reproduce this?

**Comment by DevCharly** [comment]
> Is there a particular place in the UI, like somewhere in the Preferences page, where I can reproduce this?

Unfortunately, no.
IDEA uses some kind of titled separator.
But 3rd party plugins could use `TitledBorder`.

This issue came up when using Monokai Pro in another Swing application using FlatLaf:
https://github.com/JFormDesigner/FlatLaf/issues/524

Anyway, you can reproduce it in IDEA by creating a new form (New > Swing UI Designer > GUI form), select the panel and set the property "border > title" in the properties view:

![image](https://user-images.githubusercontent.com/5604048/168306718-af63f7a1-c4ad-4593-adbb-d52c516645f1.png)

Same form in Darcula:

![image](https://user-images.githubusercontent.com/5604048/168306747-c4c459c3-c60d-4d6c-ac19-7adc80b70179.png)

**Comment by espositocode** [comment]
Despite that your issue was perfectly documented, and even pointed out exactly which field needed to be updated, I finally fixed this four months later: https://plugins.jetbrains.com/plugin/13643-monokai-pro-theme/versions/stable/216933

Thanks!
