### ISSUE TITLE
theme project file icon missing show

### ISSUE THREAD

**Issue by mrhjx2** [subtheme-dev/monokai-pro#38]
**Describe the bug**
theme file icon missing show

**To Reproduce**
switch theme old file icon not change to show

**Screenshots**
![image](https://user-images.githubusercontent.com/15726662/172895669-38cd3d64-fdc3-42de-ad34-79f320138aaa.png)
![image](https://user-images.githubusercontent.com/15726662/172895862-2fe3a544-3957-44b2-8780-0875ca09320f.png)

**Application:**
PyCharm, 2021.3.1

**Comment by espositocode** [comment]
Unfortunately, I don't have a copy of the original icons (this is an unofficial theme), so I cannot change the icons right now. If the creator open sources the icons, I would gladly bundle them here. However, Monokai Pro is a paid theme, so I don't think he would do that.
