### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by G-Cao** [subtheme-dev/monokai-pro#41]
**Describe**
The color scheme I use is 'Filter Spectrum' in monokai-pro. When using code hints, the first line is highlighted in the same color as the background color of the entire code editor, which makes it not easy to see the first line hints(often what I want) in the whole editing interface. And the first sight is the part other than the first line. Thanks.

**Screenshots**
<img width="921" alt="Snipaste_2022-09-01_10-24-07" src="https://user-images.githubusercontent.com/23249756/187819083-5a3df522-fcae-417c-90d4-afead607aad4.png">
<img width="896" alt="截屏2022-09-01 10 41 48" src="https://user-images.githubusercontent.com/23249756/187820840-79efc2c8-3db6-4295-8caf-7eccfbf6ab02.png">

**Application & System:**
PyCharm2022.2.1 on Mac OS 12.3

**Comment by espositocode** [comment]
Looking at the official VSCode theme, it seems the highlighted row use a much lighter color. I'll switch to that. Good catch.

<img width="274" alt="Screen Shot 2022-09-01 at 8 08 27 AM" src="https://user-images.githubusercontent.com/2243530/187910284-c33f5257-235a-47fe-81a9-3356b8f75ddd.png">

**Comment by espositocode** [comment]
Updated in 1.10
