### ISSUE TITLE
File icon colors

### ISSUE THREAD

**Issue by shahmilav** [subtheme-dev/monokai-pro#42]
As you can see from the screenshot (all themes, screenshot uses Filter Spectrum), the default file icons do not have theme colors. 
<img width="431" alt="Screen Shot 2022-09-11 at 3 48 19 PM" src="https://user-images.githubusercontent.com/53659750/189546287-a37fe4db-5a9b-4066-81e1-11764b035cbe.png">

Unlike [Nord](https://www.nordtheme.com/ports/jetbrains), for example:

<img width="431" alt="Screen Shot 2022-09-11 at 3 49 59 PM" src="https://user-images.githubusercontent.com/53659750/189546353-094c27f5-34e2-4308-9dd7-e2db2ff352a3.png">)

JetBrains provides a way to do this [here](https://plugins.jetbrains.com/docs/intellij/themes-customize.html#customizing-icons). It would be nice if Monokai Pro used this API for a more coherent UI.

**Comment by espositocode** [comment]
Unfortunately, I don't have access to the official icons from the Molokai Pro creator (and I don't have the skillset to create icons). For now, I would recommend installing a 3rd party plugin, such as [Atom Material Icons](https://plugins.jetbrains.com/plugin/10044-atom-material-icons).
